site_name: Proper Android UI Testing
repo_url: https://github.com/android-ui-testing/Cookbook
repo_name: Cookbook
edit_uri: tree/main/docs/content
docs_dir: 'docs/content'
remote_branch: gh-pages
language: en

theme:
  name: 'material'
  icon:
    logo: fontawesome/brands/android
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.tabs
    - content.code.annotate

extra:
  analytics:
    provider: google
    property: UA-211238769-1
  homepage: https://android-ui-testing.github.io/Cookbook/home/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/android-ui-testing/Cookbook
      name: Repository

nav:
  - Home:
      - home/index.md
  - Basics:
      - Testing theory: basics/testing_theory.md
      - Instrumented testing: basics/instrumented_testing_basics.md
      - UI testing: basics/ui_testing.md
      - Screenshot testing: basics/screenshot_testing.md
  - Practices:
      - State clearing: practices/state_clearing.md
      - Test runners: practices/test_runners_review.md
      - Emulator vs real device: practices/emulator_vs_real_device.md
      - Emulator setup: practices/emulator_setup.md
      - Network: practices/network.md
      - Flakiness: practices/flakiness.md
      - Shared test components: practices/shared_test_components.md
      - Page object: practices/page_object.md

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
