site_name: Proper Android UI Testing
repo_url: https://github.com/android-ui-testing/Cookbook
repo_name: Cookbook
edit_uri: tree/develop/docs/content
docs_dir: 'docs/content'
remote_branch: gh-pages
language: en

theme:
  name: 'material'
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs


nav:
  - Home:
      - home/index.md
  - Basics:
      - Testing theory: basics/testing_theory.md
      - Instrumented testing: basics/instrumented_testing_basics.md
  - Practices:
      - Application state: practices/state_clearing.md
      - Test runners: practices/test_runners_review.md
      - Network: practices/network.md
      - Emulator vs real device: practices/emulator_vs_real_device.md
      - Flakiness: practices/flakiness.md
      - Shared test components: practices/shared_test_components.md
      - Page object: practices/page_object.md

markdown_extensions:
  - admonition
  - pymdownx.details


